changelog:
  categories:
    - title: "User-facing changes 👀"
      labels:
        - '*'
      exclude:
        labels:
          - api changes
          - dependencies
          - feature toggled
          - technical changes only
    - title: "API changes ⚠️"
      labels:
        - api changes
    - title: "Features under construction 🚧"
      labels:
        - feature toggled
    - title: "Technical changes 🛠️"
      labels:
        - technical changes only
    - title: "Dependencies 📦"
      labels:
        - dependencies
