changelog:
  categories:
    - title: "User-facing changes 👀" # Other categories will need to be manually arrange for now.
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - feature toggled
          - technical changes only
    - title: "Experimental features for testing 😎"
        - feature toggled
    - title: "Technical changes 🔧"
      labels:
        - technical changes only
    - title: "Dependencies 📦"
      labels:
        - dependencies
