---
openapi: 3.0.1
info:
  title: OFN DFC API
  version: v0.1.7
components:
  securitySchemes:
    oidc_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: OpenID Connect token from a trusted platform
    ofn_api_token:
      type: apiKey
      in: header
      name: X-Api-Token
      description: API token of an authorized OFN user
    ofn_session:
      type: apiKey
      in: cookie
      name: _ofn_session
      description: Session cookie of a logged in OFN user
security:
- oidc_token: []
- ofn_api_token: []
- ofn_session: []
paths:
  "/api/dfc-v1.7/enterprises/{id}":
    get:
      summary: Show enterprise
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '404':
          description: not found
  "/api/dfc-v1.7/persons/{id}":
    get:
      summary: Show person
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '404':
          description: not found
servers:
- url: "/"
