---
openapi: 3.0.1
info:
  title: OFN DFC API
  version: v0.1.7
components:
  securitySchemes:
    oidc_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: OpenID Connect token from a trusted platform
    ofn_api_token:
      type: apiKey
      in: header
      name: X-Api-Token
      description: API token of an authorized OFN user
    ofn_session:
      type: apiKey
      in: cookie
      name: _ofn_session
      description: Session cookie of a logged in OFN user
security:
- oidc_token: []
- ofn_api_token: []
- ofn_session: []
paths:
  "/api/dfc-v1.7/enterprises/{id}":
    get:
      summary: Show enterprise
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    "@context": http://static.datafoodconsortium.org/ontologies/context.json
                    "@graph":
                    - "@id": http://test.host/api/dfc-v1.7/enterprises/10000
                      "@type": dfc-b:Enterprise
                      dfc-b:hasName: ''
                      dfc-b:hasDescription: ''
                      dfc-b:VATnumber: ''
                      dfc-b:supplies: http://test.host/api/dfc-v1.7/enterprises/10000/supplied_products/10001
                      dfc-b:manages: http://test.host/api/dfc-v1.7/enterprises/10000/catalog_items/10001
                    - "@id": http://test.host/api/dfc-v1.7/enterprises/10000/supplied_products/10001
                      "@type": dfc-b:SuppliedProduct
                      dfc-b:name: Apple
                      dfc-b:description: Round
                      dfc-b:hasType: dfc-pt:non-local-vegetable
                      dfc-b:hasQuantity:
                        "@type": dfc-b:QuantitativeValue
                        dfc-b:hasUnit: dfc-m:Gram
                        dfc-b:value: 1.0
                      dfc-b:alcoholPercentage: 0.0
                      dfc-b:lifetime: ''
                      dfc-b:usageOrStorageCondition: ''
                      dfc-b:totalTheoreticalStock: 0.0
                    - "@id": http://test.host/api/dfc-v1.7/enterprises/10000/catalog_items/10001
                      "@type": dfc-b:CatalogItem
                      dfc-b:references: http://test.host/api/dfc-v1.7/enterprises/10000/supplied_products/10001
                      dfc-b:sku: APP
                      dfc-b:stockLimitation: 0
                      dfc-b:offeredThrough: http://test.host/api/dfc-v1.7/enterprises/10000/offers/10001
        '404':
          description: not found
  "/api/dfc-v1.7/persons/{id}":
    get:
      summary: Show person
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    "@context": http://static.datafoodconsortium.org/ontologies/context.json
                    "@id": http://test.host/api/dfc-v1.7/persons/10000
                    "@type": dfc-b:Person
        '404':
          description: not found
  "/api/dfc-v1.7/enterprises/{enterprise_id}/supplied_products":
    parameters:
    - name: enterprise_id
      in: path
      required: true
      schema:
        type: string
    post:
      summary: Create SuppliedProduct
      parameters: []
      responses:
        '400':
          description: bad request
        '204':
          description: success
      requestBody:
        content:
          application/json:
            schema:
              example:
                "@context": http://static.datafoodconsortium.org/ontologies/context.json
                "@id": http://test.host/api/dfc-v1.7/enterprises/6201/supplied_products/0
                "@type": dfc-b:SuppliedProduct
                dfc-b:name: Apple
                dfc-b:description: A delicious heritage apple
                dfc-b:hasType: dfc-pt:non-local-vegetable
                dfc-b:hasQuantity:
                  "@type": dfc-b:QuantitativeValue
                  dfc-b:hasUnit: dfc-m:Gram
                  dfc-b:value: 3.0
                dfc-b:alcoholPercentage: 0.0
                dfc-b:lifetime: ''
                dfc-b:usageOrStorageCondition: ''
                dfc-b:totalTheoreticalStock: 0.0
  "/api/dfc-v1.7/enterprises/{enterprise_id}/supplied_products/{id}":
    parameters:
    - name: enterprise_id
      in: path
      required: true
      schema:
        type: string
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Show SuppliedProduct
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                test_example:
                  value:
                    "@context": http://static.datafoodconsortium.org/ontologies/context.json
                    "@id": http://test.host/api/dfc-v1.7/enterprises/10000/supplied_products/10001
                    "@type": dfc-b:SuppliedProduct
                    dfc-b:name: Pesto
                    dfc-b:description: Basil Pesto
                    dfc-b:hasType: dfc-pt:non-local-vegetable
                    dfc-b:hasQuantity:
                      "@type": dfc-b:QuantitativeValue
                      dfc-b:hasUnit: dfc-m:Gram
                      dfc-b:value: 1.0
                    dfc-b:alcoholPercentage: 0.0
                    dfc-b:lifetime: ''
                    dfc-b:usageOrStorageCondition: ''
                    dfc-b:totalTheoreticalStock: 0.0
        '404':
          description: not found
    put:
      summary: Update SuppliedProduct
      parameters: []
      responses:
        '401':
          description: unauthorized
        '204':
          description: success
      requestBody:
        content:
          application/json:
            schema: {}
servers:
- url: "/"
