name: "Deploy to Staging"

on:
  pull_request_target:
    types: [labeled]
  workflow_dispatch:
    inputs:
      server:
        description: "Staging Server"
        type: choice
        required: true
        options:
          - staging.openfoodnetwork.org.uk
          - staging.openfoodnetwork.org.au
          - staging.coopcircuits.fr

jobs:
  deploy_pr:
    if: contains(fromJSON('["pr-staged-uk", "pr-staged-au", "pr-staged-fr"]'), github.event.label.name)
    runs-on: ubuntu-latest
    steps:
      - name: Configure deployment key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.DEPLOYMENT_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.DEPLOYMENT_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy to Staging
        run: |
          ssh ofn-deploy@${{ github.event.label.description }} -o LogLevel=ERROR "pull-request-${{ github.event.pull_request.number }} ."

  deploy_branch:
    if: ${{ inputs.server }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure deployment key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.DEPLOYMENT_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.DEPLOYMENT_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy to Staging
        run: |
          ssh ofn-deploy@${{ inputs.server }} -o LogLevel=ERROR "$GITHUB_REF_NAME $GITHUB_SHA"
